# 4. The Syracuse (also called "Collatz" or "Hailstone") sequence is generated by starting with a natural number and repeatedly
# applying the following function until reaching 1:
#                        syr(x) =
#                         {
#                           x/2 if x is even
#                           3x + 1 if x is odd
#                          }
# For example, the Syracuse sequence starting with 5 is: 5, 16, 8, 4, 2, 1. It is
# an open question in mathematics whether this sequence will always go to 1 for every possible starting value.
# Write a program that gets a starting value from the user and then prints
# the Syracuse sequence for that starting value.

# input: user entered number
# output: print out the sequence number calc step until it reaches 1

# algorithm:
# get user entered number and assign the value
# create while loop with exit condition Syracuse number equal to 1
#   create if statement to determine if the Syracuse number is Odd or Even using remainder %
#   execute formula for even numbers based on the parent condition above
#        print the result
#   execute formula for odd numbers based on the parent condition above
#        print the result

def main():
    x = float(input("Enter the number to do Syracuse sequencing: "))
    while x != 1:
        print(x, end=' ')
        if (x % 2 == 0):
            x = x / 2
        else:
            x = 3 * x + 1
    print(1.0, end= ' ')

if __name__ == '__main__':
    main()
